### ISSUE TITLE
헤더 구현하기

### ISSUE THREAD

**Issue by DingX2** [UdongSari/frontend#7]
![image](https://github.com/UdongSari/frontend/assets/96682768/a5f3059d-13da-441f-b712-f06baea655ed)
- 헤더만들기
- 로고는 추후에 만들자!

**Comment by toothlessdev** [comment]
<img width="1345" alt="image" src="https://github.com/UdongSari/frontend/assets/52105661/2f985278-3773-4da7-a403-955a9948fa89">
구현완료
